.TH AGHILBIT-CLI "1" "February 2016" "aghilbit-cli 0.12"
.SH NAME
aghilbit-cli \- a remote procedure call client for Aghilbit Core. 
.SH SYNOPSIS
aghilbit-cli [options] <command> [params] \- Send command to Aghilbit Core. 
.TP
aghilbit-cli [options] help \- Asks Aghilbit Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the aghilbit-cli program. aghilbit-cli is an RPC client used to send commands to Aghilbit Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBaghilbitd\fP, \fBaghilbit.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
